import type { Module } from '../types';

export const ebikeBasics: Module = {
  slug: 'ebike-basics',
  title: {
    en: 'eBike Basics',
    es: 'Lo básico de la eBike',
    it: "Nozioni di base sull'eBike",
    nl: 'eBike-basis',
    fr: "Les bases de l'eBike",
    ca: "Els bàsics de l'eBike",
    pt: 'Noções básicas da eBike',
  },
  description: {
    en: 'New to electric bikes? This module walks you through how a Cooltra eBike works, how to get started, and how to ride and stop safely.',
    es: '¿Nuevo en las bicicletas eléctricas? Este módulo te explica cómo funciona una eBike de Cooltra, cómo empezar y cómo conducir y frenar de forma segura.',
    it: "Sei alle prime armi con le bici elettriche? Questo modulo ti spiega come funziona una eBike Cooltra, come iniziare e come guidare e frenare in sicurezza.",
    nl: 'Nieuw met elektrische fietsen? Deze module legt je uit hoe een Cooltra eBike werkt, hoe je begint en hoe je veilig rijdt en remt.',
    fr: "Nouveau dans les vélos électriques ? Ce module vous explique comment fonctionne une eBike Cooltra, comment démarrer et comment rouler et freiner en toute sécurité.",
    ca: "Ets nou en les bicicletes elèctriques? Aquest mòdul t'explica com funciona una eBike de Cooltra, com començar i com conduir i frenar de manera segura.",
    pt: 'Novo nas bicicletas elétricas? Este módulo explica como funciona uma eBike da Cooltra, como começar e como conduzir e travar com segurança.',
  },
  lessons: [
    {
      title: {
        en: 'Your Cooltra eBike',
        es: 'Tu eBike de Cooltra',
        it: 'La tua eBike Cooltra',
        nl: 'Jouw Cooltra eBike',
        fr: 'Votre eBike Cooltra',
        ca: 'La teva eBike de Cooltra',
        pt: 'A tua eBike da Cooltra',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'An electric bike is a regular bicycle with an integrated electric motor that gives you a boost when you pedal. The motor assists your pedalling up to 25 km/h — perfect for getting around the city without breaking a sweat.',
            es: 'Una bicicleta eléctrica es una bicicleta normal con un motor eléctrico integrado que te da un empujón cuando pedaleas. El motor te asiste hasta los 25 km/h, perfecto para moverte por la ciudad sin sudar.',
            it: "Una bicicletta elettrica è una normale bicicletta con un motore elettrico integrato che ti dà una spinta quando pedali. Il motore assiste la tua pedalata fino a 25 km/h, perfetto per muoverti in città senza fare fatica.",
            nl: 'Een elektrische fiets is een gewone fiets met een geïntegreerde elektromotor die je een duwtje geeft als je trapt. De motor ondersteunt je trappen tot 25 km/h — perfect om je door de stad te verplaatsen zonder te zweten.',
            fr: "Un vélo électrique est un vélo classique doté d'un moteur électrique intégré qui vous donne un coup de pouce lorsque vous pédalez. Le moteur assiste votre pédalage jusqu'à 25 km/h — parfait pour se déplacer en ville sans transpirer.",
            ca: "Una bicicleta elèctrica és una bicicleta normal amb un motor elèctric integrat que et dóna una empenta quan pedales. El motor t'assisteix en el pedaleig fins als 25 km/h, perfecte per moure't per la ciutat sense suar.",
            pt: 'Uma bicicleta elétrica é uma bicicleta normal com um motor elétrico integrado que te dá um impulso quando pedalas. O motor assiste o teu pedalar até aos 25 km/h — perfeito para te moveres pela cidade sem te cansares.',
          },
        },
      ],
    },
    {
      title: {
        en: 'How pedal assist works',
        es: 'Cómo funciona la asistencia al pedaleo',
        it: 'Come funziona la pedalata assistita',
        nl: 'Hoe trapondersteuning werkt',
        fr: "Comment fonctionne l'assistance au pédalage",
        ca: 'Com funciona l\'assistència al pedaleig',
        pt: 'Como funciona a assistência ao pedal',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Start pedalling and the motor activates automatically. The motor cuts out at 25 km/h so you are always in control. Use the handlebar display to switch between assist levels.',
            es: 'Empieza a pedalear y el motor se activa automáticamente. El motor se corta a 25 km/h para que siempre tengas el control. Usa la pantalla del manillar para cambiar entre niveles de asistencia.',
            it: 'Inizia a pedalare e il motore si attiva automaticamente. Il motore si interrompe a 25 km/h così sei sempre tu ad avere il controllo. Usa il display sul manubrio per cambiare livello di assistenza.',
            nl: 'Begin met trappen en de motor schakelt automatisch in. De motor stopt bij 25 km/h zodat je altijd de controle houdt. Gebruik het stuurdisplay om tussen ondersteuningsniveaus te wisselen.',
            fr: "Commencez à pédaler et le moteur s'active automatiquement. Le moteur se coupe à 25 km/h pour que vous gardiez toujours le contrôle. Utilisez l'écran du guidon pour changer de niveau d'assistance.",
            ca: "Comença a pedalar i el motor s'activa automàticament. El motor es talla a 25 km/h perquè sempre tinguis el control. Fes servir la pantalla del manillar per canviar entre nivells d'assistència.",
            pt: 'Começa a pedalar e o motor ativa-se automaticamente. O motor corta aos 25 km/h para que tenhas sempre o controlo. Usa o ecrã do guiador para alternar entre níveis de assistência.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Stopping safely',
        es: 'Frenar de forma segura',
        it: 'Frenare in sicurezza',
        nl: 'Veilig stoppen',
        fr: "S'arrêter en toute sécurité",
        ca: 'Frenar de manera segura',
        pt: 'Travar com segurança',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Your Cooltra eBike has brake levers on both handlebars. Always squeeze both at the same time, gently and progressively. Allow extra stopping distance at higher speeds.',
            es: 'Tu eBike de Cooltra tiene manetas de freno en ambos lados del manillar. Aprieta siempre las dos a la vez, con suavidad y de forma progresiva. Deja más distancia de frenado a velocidades altas.',
            it: 'La tua eBike Cooltra ha le leve del freno su entrambi i lati del manubrio. Stringile sempre tutte e due contemporaneamente, in modo dolce e progressivo. Lascia più spazio di frenata alle velocità più elevate.',
            nl: 'Jouw Cooltra eBike heeft remhendels aan beide kanten van het stuur. Knijp altijd beide tegelijk in, zachtjes en geleidelijk. Houd extra remafstand aan bij hogere snelheden.',
            fr: "Votre eBike Cooltra possède des leviers de frein des deux côtés du guidon. Serrez toujours les deux en même temps, doucement et progressivement. Prévoyez une distance de freinage supplémentaire à vitesse élevée.",
            ca: "La teva eBike de Cooltra té manetes de fre a tots dos costats del manillar. Prem sempre les dues alhora, amb suavitat i de manera progressiva. Deixa més distància de frenada a velocitats altes.",
            pt: 'A tua eBike da Cooltra tem manetes de travão em ambos os lados do guiador. Aperta sempre as duas ao mesmo tempo, com suavidade e de forma progressiva. Deixa mais distância de travagem a velocidades elevadas.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Before every ride',
        es: 'Antes de cada trayecto',
        it: 'Prima di ogni viaggio',
        nl: 'Voor elke rit',
        fr: 'Avant chaque trajet',
        ca: 'Abans de cada trajecte',
        pt: 'Antes de cada viagem',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Check that the brakes feel firm.',
              es: 'Comprueba que los frenos respondan con firmeza.',
              it: 'Controlla che i freni rispondano con fermezza.',
              nl: 'Controleer of de remmen stevig aanvoelen.',
              fr: 'Vérifiez que les freins répondent fermement.',
              ca: 'Comprova que els frens responguin amb fermesa.',
              pt: 'Verifica se os travões respondem com firmeza.',
            },
            {
              en: 'Confirm the battery has enough charge.',
              es: 'Confirma que la batería tenga carga suficiente.',
              it: 'Verifica che la batteria abbia carica sufficiente.',
              nl: 'Bevestig dat de batterij voldoende lading heeft.',
              fr: "Confirmez que la batterie a suffisamment de charge.",
              ca: 'Confirma que la bateria tingui prou càrrega.',
              pt: 'Confirma que a bateria tem carga suficiente.',
            },
            {
              en: 'Adjust the saddle height to your comfort.',
              es: 'Ajusta la altura del sillín a tu comodidad.',
              it: 'Regola l\'altezza della sella in base al tuo comfort.',
              nl: 'Stel de zadelhoogte naar wens af.',
              fr: 'Réglez la hauteur de la selle selon votre confort.',
              ca: 'Ajusta l\'alçada del seient a la teva comoditat.',
              pt: 'Ajusta a altura do selim ao teu conforto.',
            },
            {
              en: 'Look for any visible damage and report it in the app.',
              es: 'Revisa si hay daños visibles y repórtalos en la app.',
              it: "Controlla se ci sono danni visibili e segnalali nell'app.",
              nl: 'Kijk of er zichtbare schade is en meld dit in de app.',
              fr: "Recherchez tout dommage visible et signalez-le dans l'application.",
              ca: "Revisa si hi ha danys visibles i informa'n a l'app.",
              pt: 'Procura quaisquer danos visíveis e reporta-os na app.',
            },
          ],
        },
      ],
    },
    {
      title: {
        en: 'Parking your eBike',
        es: 'Aparcar tu eBike',
        it: 'Parcheggiare la tua eBike',
        nl: 'Je eBike parkeren',
        fr: 'Garer votre eBike',
        ca: 'Aparcar la teva eBike',
        pt: 'Estacionar a tua eBike',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Always end your ride in an authorised parking area. Use the kickstand to park upright. Take a photo in the app to confirm the bike is parked correctly. Never block ramps, doorways, or pedestrian paths.',
            es: 'Termina siempre tu trayecto en una zona de aparcamiento autorizada. Usa el caballete para aparcar en posición vertical. Haz una foto en la app para confirmar que la bici está bien aparcada. Nunca bloquees rampas, puertas ni pasos de peatones.',
            it: "Termina sempre il tuo viaggio in un'area di parcheggio autorizzata. Usa il cavalletto per parcheggiare in posizione verticale. Scatta una foto nell'app per confermare che la bici è parcheggiata correttamente. Non bloccare mai rampe, porte o passaggi pedonali.",
            nl: 'Beëindig je rit altijd in een toegestane parkeerzone. Gebruik de standaard om rechtop te parkeren. Maak een foto in de app om te bevestigen dat de fiets correct geparkeerd staat. Blokkeer nooit hellingen, deuropeningen of voetpaden.',
            fr: "Terminez toujours votre trajet dans une zone de stationnement autorisée. Utilisez la béquille pour garer le vélo à la verticale. Prenez une photo dans l'application pour confirmer que le vélo est bien garé. Ne bloquez jamais les rampes, les portes ou les voies piétonnes.",
            ca: "Acaba sempre el teu trajecte en una zona d'aparcament autoritzada. Fes servir el cavallet per aparcar en posició vertical. Fes una foto a l'app per confirmar que la bici està ben aparcada. No bloquegis mai rampes, portes ni passos de vianants.",
            pt: 'Termina sempre a tua viagem numa zona de estacionamento autorizada. Usa o descanso para estacionar na vertical. Tira uma foto na app para confirmar que a bicicleta está bem estacionada. Nunca bloqueies rampas, portas ou passagens de peões.',
          },
        },
      ],
    },
  ],
  quiz: [
    {
      prompt: {
        en: 'At what speed does the electric motor stop assisting?',
        es: '¿A qué velocidad deja de asistir el motor eléctrico?',
        it: 'A quale velocità il motore elettrico smette di assistere?',
        nl: 'Bij welke snelheid stopt de elektromotor met ondersteunen?',
        fr: "À quelle vitesse le moteur électrique cesse-t-il d'assister ?",
        ca: 'A quina velocitat deixa d\'assistir el motor elèctric?',
        pt: 'A que velocidade o motor elétrico deixa de assistir?',
      },
      options: [
        {
          id: 'a',
          label: { en: '15 km/h', es: '15 km/h', it: '15 km/h', nl: '15 km/h', fr: '15 km/h', ca: '15 km/h', pt: '15 km/h' },
        },
        {
          id: 'b',
          label: { en: '25 km/h', es: '25 km/h', it: '25 km/h', nl: '25 km/h', fr: '25 km/h', ca: '25 km/h', pt: '25 km/h' },
        },
        {
          id: 'c',
          label: { en: '35 km/h', es: '35 km/h', it: '35 km/h', nl: '35 km/h', fr: '35 km/h', ca: '35 km/h', pt: '35 km/h' },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'The motor assists you up to 25 km/h and then cuts out, so you stay in control.',
        es: 'El motor te asiste hasta los 25 km/h y luego se corta, para que mantengas el control.',
        it: 'Il motore ti assiste fino a 25 km/h e poi si interrompe, così mantieni il controllo.',
        nl: 'De motor ondersteunt je tot 25 km/h en stopt dan, zodat je de controle houdt.',
        fr: "Le moteur vous assiste jusqu'à 25 km/h puis se coupe, pour que vous gardiez le contrôle.",
        ca: 'El motor t\'assisteix fins als 25 km/h i després es talla, perquè mantinguis el control.',
        pt: 'O motor assiste-te até aos 25 km/h e depois corta, para que mantenhas o controlo.',
      },
    },
    {
      prompt: {
        en: 'Where are the brake levers on a Cooltra eBike?',
        es: '¿Dónde están las manetas de freno en una eBike de Cooltra?',
        it: 'Dove si trovano le leve del freno su una eBike Cooltra?',
        nl: 'Waar zitten de remhendels op een Cooltra eBike?',
        fr: 'Où se trouvent les leviers de frein sur une eBike Cooltra ?',
        ca: 'On són les manetes de fre en una eBike de Cooltra?',
        pt: 'Onde estão as manetes de travão numa eBike da Cooltra?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Front wheel only',
            es: 'Solo la rueda delantera',
            it: 'Solo la ruota anteriore',
            nl: 'Alleen het voorwiel',
            fr: 'La roue avant uniquement',
            ca: 'Només la roda davantera',
            pt: 'Apenas a roda dianteira',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Both handlebars',
            es: 'En ambos lados del manillar',
            it: 'Su entrambi i lati del manubrio',
            nl: 'Aan beide kanten van het stuur',
            fr: 'Des deux côtés du guidon',
            ca: 'A tots dos costats del manillar',
            pt: 'Em ambos os lados do guiador',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Rear wheel only',
            es: 'Solo la rueda trasera',
            it: 'Solo la ruota posteriore',
            nl: 'Alleen het achterwiel',
            fr: 'La roue arrière uniquement',
            ca: 'Només la roda del darrere',
            pt: 'Apenas a roda traseira',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'There is a lever on each side of the handlebar. Squeeze both at the same time to brake safely.',
        es: 'Hay una maneta a cada lado del manillar. Aprieta las dos a la vez para frenar con seguridad.',
        it: "C'è una leva su ogni lato del manubrio. Stringile entrambe contemporaneamente per frenare in sicurezza.",
        nl: 'Er zit aan elke kant van het stuur een hendel. Knijp beide tegelijk in om veilig te remmen.',
        fr: "Il y a un levier de chaque côté du guidon. Serrez les deux en même temps pour freiner en toute sécurité.",
        ca: "Hi ha una maneta a cada costat del manillar. Prem les dues alhora per frenar amb seguretat.",
        pt: 'Há uma manete de cada lado do guiador. Aperta as duas ao mesmo tempo para travar com segurança.',
      },
    },
    {
      prompt: {
        en: 'What should you do before every ride?',
        es: '¿Qué deberías hacer antes de cada trayecto?',
        it: 'Cosa dovresti fare prima di ogni viaggio?',
        nl: 'Wat moet je voor elke rit doen?',
        fr: 'Que devez-vous faire avant chaque trajet ?',
        ca: 'Què hauries de fer abans de cada trajecte?',
        pt: 'O que deves fazer antes de cada viagem?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Just start riding',
            es: 'Simplemente empezar a conducir',
            it: 'Iniziare semplicemente a guidare',
            nl: 'Gewoon beginnen met rijden',
            fr: 'Simplement commencer à rouler',
            ca: 'Simplement començar a conduir',
            pt: 'Simplesmente começar a conduzir',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Do a basic safety check',
            es: 'Hacer una comprobación básica de seguridad',
            it: 'Fare un controllo di sicurezza di base',
            nl: 'Een basisveiligheidscontrole doen',
            fr: 'Faire une vérification de sécurité de base',
            ca: 'Fer una comprovació bàsica de seguretat',
            pt: 'Fazer uma verificação básica de segurança',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Check the weather app',
            es: 'Mirar la app del tiempo',
            it: "Controllare l'app del meteo",
            nl: 'De weer-app checken',
            fr: "Consulter l'application météo",
            ca: "Mirar l'app del temps",
            pt: 'Consultar a app do tempo',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'A quick check of brakes, battery and saddle keeps you safe before you set off.',
        es: 'Una comprobación rápida de frenos, batería y sillín te mantiene seguro antes de salir.',
        it: 'Un rapido controllo di freni, batteria e sella ti tiene al sicuro prima di partire.',
        nl: 'Een snelle controle van remmen, batterij en zadel houdt je veilig voordat je vertrekt.',
        fr: "Une vérification rapide des freins, de la batterie et de la selle vous garde en sécurité avant de partir.",
        ca: 'Una comprovació ràpida de frens, bateria i seient et manté segur abans de sortir.',
        pt: 'Uma verificação rápida dos travões, bateria e selim mantém-te seguro antes de partires.',
      },
    },
  ],
};
