import type { Module } from '../types';

export const realWorldScenarios: Module = {
  slug: 'real-world-scenarios',
  title: {
    en: 'Real-World Scenarios',
    es: 'Situaciones reales',
    it: 'Situazioni reali',
    nl: 'Praktijksituaties',
    fr: 'Situations réelles',
    ca: 'Situacions reals',
    pt: 'Situações reais',
  },
  description: {
    en: 'Awareness of your surroundings keeps you safe. This module covers lane positioning, signalling, overtaking, right of way, pedestrian crossings and large vehicles.',
    es: 'Estar atento a tu entorno te mantiene seguro. Este módulo trata el posicionamiento en el carril, las señales, los adelantamientos, la prioridad, los pasos de peatones y los vehículos grandes.',
    it: 'Essere consapevoli di ciò che ti circonda ti tiene al sicuro. Questo modulo tratta il posizionamento nella corsia, la segnalazione, i sorpassi, la precedenza, gli attraversamenti pedonali e i veicoli di grandi dimensioni.',
    nl: 'Bewust zijn van je omgeving houdt je veilig. Deze module behandelt je positie op de rijbaan, signaleren, inhalen, voorrang, voetgangersoversteekplaatsen en grote voertuigen.',
    fr: 'Être attentif à votre environnement vous protège. Ce module aborde le positionnement sur la voie, la signalisation, les dépassements, la priorité, les passages piétons et les véhicules de grande taille.',
    ca: 'Estar atent a l\'entorn et manté segur. Aquest mòdul tracta el posicionament al carril, la senyalització, els avançaments, la prioritat, els passos de vianants i els vehicles grans.',
    pt: 'Estar atento ao que o rodeia mantém-no seguro. Este módulo aborda o posicionamento na faixa, a sinalização, as ultrapassagens, a prioridade, as passadeiras e os veículos grandes.',
  },
  lessons: [
    {
      title: {
        en: 'Lane positioning',
        es: 'Posición en el carril',
        it: 'Posizionamento nella corsia',
        nl: 'Positie op de rijbaan',
        fr: 'Positionnement sur la voie',
        ca: 'Posició al carril',
        pt: 'Posicionamento na faixa',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Ride in a predictable line within your lane and keep a safe distance from parked cars to avoid opening doors. On unmarked roads, stay to the right but far enough out to be seen.',
            es: 'Circula en una línea previsible dentro de tu carril y mantén una distancia segura de los coches aparcados para evitar puertas que se abren. En vías sin marcas, mantente a la derecha pero lo bastante separado para que te vean.',
            it: 'Procedi su una traiettoria prevedibile all\'interno della tua corsia e mantieni una distanza di sicurezza dalle auto parcheggiate per evitare le portiere che si aprono. Sulle strade senza segnaletica, tieni la destra ma abbastanza distante da essere visto.',
            nl: 'Rijd in een voorspelbare lijn binnen je rijstrook en houd voldoende afstand tot geparkeerde auto\'s om openslaande portieren te vermijden. Op wegen zonder markering houd je rechts, maar ver genoeg uit de kant om gezien te worden.',
            fr: 'Roulez selon une trajectoire prévisible dans votre voie et gardez une distance de sécurité avec les voitures stationnées pour éviter les portières qui s\'ouvrent. Sur les routes non marquées, tenez votre droite mais suffisamment éloigné pour être vu.',
            ca: 'Circula en una línia previsible dins del teu carril i mantén una distància segura dels cotxes aparcats per evitar portes que s\'obren. A les vies sense marques, mantén-te a la dreta però prou separat perquè et vegin.',
            pt: 'Circule numa linha previsível dentro da sua faixa e mantenha uma distância segura dos carros estacionados para evitar portas que se abrem. Em vias sem marcações, mantenha-se à direita mas afastado o suficiente para ser visto.',
          },
        },
      ],
    },
    {
      title: {
        en: 'When to signal',
        es: 'Cuándo señalizar',
        it: 'Quando segnalare',
        nl: 'Wanneer signaleren',
        fr: 'Quand signaler',
        ca: 'Quan senyalitzar',
        pt: 'Quando sinalizar',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Before turning left or right.',
              es: 'Antes de girar a la izquierda o a la derecha.',
              it: 'Prima di svoltare a sinistra o a destra.',
              nl: 'Voordat je naar links of rechts afslaat.',
              fr: 'Avant de tourner à gauche ou à droite.',
              ca: 'Abans de girar a l\'esquerra o a la dreta.',
              pt: 'Antes de virar à esquerda ou à direita.',
            },
            {
              en: 'Before changing lanes.',
              es: 'Antes de cambiar de carril.',
              it: 'Prima di cambiare corsia.',
              nl: 'Voordat je van rijstrook wisselt.',
              fr: 'Avant de changer de voie.',
              ca: 'Abans de canviar de carril.',
              pt: 'Antes de mudar de faixa.',
            },
            {
              en: 'Before overtaking or pulling over.',
              es: 'Antes de adelantar o detenerte a un lado.',
              it: 'Prima di sorpassare o accostare.',
              nl: 'Voordat je inhaalt of naar de kant gaat.',
              fr: 'Avant de dépasser ou de vous arrêter sur le côté.',
              ca: 'Abans d\'avançar o aturar-te a un costat.',
              pt: 'Antes de ultrapassar ou encostar.',
            },
            {
              en: 'Before leaving a roundabout.',
              es: 'Antes de salir de una rotonda.',
              it: 'Prima di uscire da una rotatoria.',
              nl: 'Voordat je een rotonde verlaat.',
              fr: 'Avant de quitter un rond-point.',
              ca: 'Abans de sortir d\'una rotonda.',
              pt: 'Antes de sair de uma rotunda.',
            },
          ],
        },
      ],
    },
    {
      title: {
        en: 'Overtaking safely',
        es: 'Adelantar con seguridad',
        it: 'Sorpassare in sicurezza',
        nl: 'Veilig inhalen',
        fr: 'Dépasser en toute sécurité',
        ca: 'Avançar amb seguretat',
        pt: 'Ultrapassar em segurança',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Overtake on the left (in right-hand traffic). Signal first, check the opposite lane is clear, and only pass when you have enough space and visibility.',
            es: 'Adelanta por la izquierda (en circulación por la derecha). Señaliza primero, comprueba que el carril contrario esté libre y adelanta solo cuando tengas espacio y visibilidad suficientes.',
            it: 'Sorpassa a sinistra (con circolazione a destra). Segnala prima, controlla che la corsia opposta sia libera e sorpassa solo quando hai spazio e visibilità sufficienti.',
            nl: 'Haal links in (bij rechts rijdend verkeer). Geef eerst richting aan, controleer of de tegenoverliggende rijstrook vrij is en haal alleen in als je voldoende ruimte en zicht hebt.',
            fr: 'Dépassez par la gauche (en circulation à droite). Signalez d\'abord, vérifiez que la voie opposée est libre et ne dépassez que lorsque vous avez assez d\'espace et de visibilité.',
            ca: 'Avança per l\'esquerra (en circulació per la dreta). Senyalitza primer, comprova que el carril contrari estigui lliure i avança només quan tinguis prou espai i visibilitat.',
            pt: 'Ultrapasse pela esquerda (em circulação pela direita). Sinalize primeiro, verifique se a faixa oposta está livre e ultrapasse apenas quando tiver espaço e visibilidade suficientes.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Right of way at intersections',
        es: 'Prioridad en las intersecciones',
        it: 'Precedenza agli incroci',
        nl: 'Voorrang op kruispunten',
        fr: 'Priorité aux intersections',
        ca: 'Prioritat a les interseccions',
        pt: 'Prioridade nos cruzamentos',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Unless signs or signals say otherwise, give way to traffic coming from your right. Make eye contact with drivers and never assume they have seen you.',
            es: 'Salvo que las señales indiquen lo contrario, cede el paso al tráfico que viene por tu derecha. Haz contacto visual con los conductores y nunca des por hecho que te han visto.',
            it: 'Salvo che i segnali indichino diversamente, dai la precedenza al traffico che proviene dalla tua destra. Stabilisci un contatto visivo con i conducenti e non dare mai per scontato che ti abbiano visto.',
            nl: 'Tenzij borden of signalen anders aangeven, verleen je voorrang aan verkeer dat van rechts komt. Maak oogcontact met bestuurders en ga er nooit van uit dat ze je gezien hebben.',
            fr: 'Sauf indication contraire des panneaux ou des feux, cédez le passage au trafic venant de votre droite. Établissez un contact visuel avec les conducteurs et ne supposez jamais qu\'ils vous ont vu.',
            ca: 'Llevat que els senyals indiquin el contrari, cedeix el pas al trànsit que ve per la teva dreta. Estableix contacte visual amb els conductors i no donis mai per fet que t\'han vist.',
            pt: 'Salvo indicação em contrário dos sinais, ceda a passagem ao trânsito que vem da sua direita. Estabeleça contacto visual com os condutores e nunca assuma que o viram.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Pedestrian crossings and buses',
        es: 'Pasos de peatones y autobuses',
        it: 'Attraversamenti pedonali e autobus',
        nl: 'Voetgangersoversteekplaatsen en bussen',
        fr: 'Passages piétons et autobus',
        ca: 'Passos de vianants i autobusos',
        pt: 'Passadeiras e autocarros',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Pedestrians always have priority at crossings — slow down, stop and, where required, dismount and walk across. Give way to buses pulling out from their stops.',
            es: 'Los peatones tienen siempre prioridad en los pasos: reduce la velocidad, detente y, donde sea obligatorio, baja y cruza andando. Cede el paso a los autobuses que salen de sus paradas.',
            it: 'I pedoni hanno sempre la precedenza sugli attraversamenti: rallenta, fermati e, dove richiesto, scendi e attraversa a piedi. Dai la precedenza agli autobus che ripartono dalle fermate.',
            nl: 'Voetgangers hebben altijd voorrang op oversteekplaatsen — vertraag, stop en stap waar nodig af en steek lopend over. Verleen voorrang aan bussen die van hun halte wegrijden.',
            fr: 'Les piétons ont toujours la priorité aux passages : ralentissez, arrêtez-vous et, lorsque c\'est requis, descendez et traversez à pied. Cédez le passage aux autobus qui quittent leur arrêt.',
            ca: 'Els vianants tenen sempre prioritat als passos: redueix la velocitat, atura\'t i, on sigui obligatori, baixa i creua a peu. Cedeix el pas als autobusos que surten de les seves parades.',
            pt: 'Os peões têm sempre prioridade nas passadeiras: reduza a velocidade, pare e, onde for obrigatório, desça e atravesse a pé. Ceda a passagem aos autocarros que saem das suas paragens.',
          },
        },
      ],
    },
  ],
  quiz: [
    {
      prompt: {
        en: 'You approach a pedestrian crossing with people waiting. What do you do?',
        es: 'Te acercas a un paso de peatones con gente esperando. ¿Qué haces?',
        it: 'Ti avvicini a un attraversamento pedonale con persone in attesa. Cosa fai?',
        nl: 'Je nadert een voetgangersoversteekplaats waar mensen staan te wachten. Wat doe je?',
        fr: 'Vous approchez d\'un passage piéton où des personnes attendent. Que faites-vous ?',
        ca: 'T\'acostes a un pas de vianants amb gent esperant. Què fas?',
        pt: 'Aproxima-se de uma passadeira com pessoas à espera. O que faz?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Ride through quickly',
            es: 'Pasar rápido',
            it: 'Passare velocemente',
            nl: 'Snel doorrijden',
            fr: 'Passer rapidement',
            ca: 'Passar ràpid',
            pt: 'Passar rapidamente',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Stop and give way',
            es: 'Detenerte y ceder el paso',
            it: 'Fermarsi e dare la precedenza',
            nl: 'Stoppen en voorrang verlenen',
            fr: 'S\'arrêter et céder le passage',
            ca: 'Aturar-te i cedir el pas',
            pt: 'Parar e ceder a passagem',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'Pedestrians have priority. Stop and let them cross safely before you continue.',
        es: 'Los peatones tienen prioridad. Detente y déjalos cruzar con seguridad antes de continuar.',
        it: 'I pedoni hanno la precedenza. Fermati e lasciali attraversare in sicurezza prima di proseguire.',
        nl: 'Voetgangers hebben voorrang. Stop en laat ze veilig oversteken voordat je verder rijdt.',
        fr: 'Les piétons ont la priorité. Arrêtez-vous et laissez-les traverser en sécurité avant de continuer.',
        ca: 'Els vianants tenen prioritat. Atura\'t i deixa\'ls creuar amb seguretat abans de continuar.',
        pt: 'Os peões têm prioridade. Pare e deixe-os atravessar em segurança antes de continuar.',
      },
    },
    {
      prompt: {
        en: 'When overtaking, which side do you pass on (right-hand traffic)?',
        es: 'Al adelantar, ¿por qué lado pasas (circulación por la derecha)?',
        it: 'Quando sorpassi, da che lato passi (circolazione a destra)?',
        nl: 'Aan welke kant haal je in (bij rechts rijdend verkeer)?',
        fr: 'En dépassant, de quel côté passez-vous (circulation à droite) ?',
        ca: 'En avançar, per quin costat passes (circulació per la dreta)?',
        pt: 'Ao ultrapassar, por que lado passa (circulação pela direita)?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Right',
            es: 'Por la derecha',
            it: 'A destra',
            nl: 'Rechts',
            fr: 'Par la droite',
            ca: 'Per la dreta',
            pt: 'Pela direita',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Left',
            es: 'Por la izquierda',
            it: 'A sinistra',
            nl: 'Links',
            fr: 'Par la gauche',
            ca: 'Per l\'esquerra',
            pt: 'Pela esquerda',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Either side',
            es: 'Por cualquier lado',
            it: 'Da entrambi i lati',
            nl: 'Aan beide kanten',
            fr: 'De n\'importe quel côté',
            ca: 'Per qualsevol costat',
            pt: 'Por qualquer lado',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'In right-hand traffic you overtake on the left, after signalling and checking it is clear.',
        es: 'En circulación por la derecha se adelanta por la izquierda, tras señalizar y comprobar que está despejado.',
        it: 'Con circolazione a destra si sorpassa a sinistra, dopo aver segnalato e controllato che sia libero.',
        nl: 'Bij rechts rijdend verkeer haal je links in, na het geven van richting en het controleren of het vrij is.',
        fr: 'En circulation à droite, on dépasse par la gauche, après avoir signalé et vérifié que la voie est libre.',
        ca: 'En circulació per la dreta s\'avança per l\'esquerra, després de senyalitzar i comprovar que està lliure.',
        pt: 'Em circulação pela direita ultrapassa-se pela esquerda, depois de sinalizar e verificar que está livre.',
      },
    },
    {
      prompt: {
        en: 'A car is approaching as you need to cross. How should you cross?',
        es: 'Se acerca un coche y necesitas cruzar. ¿Cómo deberías cruzar?',
        it: 'Un\'auto si avvicina mentre devi attraversare. Come dovresti attraversare?',
        nl: 'Er nadert een auto terwijl je moet oversteken. Hoe steek je over?',
        fr: 'Une voiture approche alors que vous devez traverser. Comment devez-vous traverser ?',
        ca: 'S\'acosta un cotxe i necessites creuar. Com hauries de creuar?',
        pt: 'Aproxima-se um carro quando precisa de atravessar. Como deve atravessar?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Speed up to cross first',
            es: 'Acelerar para cruzar primero',
            it: 'Accelerare per attraversare per primo',
            nl: 'Versnellen om als eerste over te steken',
            fr: 'Accélérer pour traverser en premier',
            ca: 'Accelerar per creuar primer',
            pt: 'Acelerar para atravessar primeiro',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Slow down and make sure the car stops',
            es: 'Reducir y asegurarte de que el coche se detiene',
            it: 'Rallentare e assicurarsi che l\'auto si fermi',
            nl: 'Vertragen en zorgen dat de auto stopt',
            fr: 'Ralentir et s\'assurer que la voiture s\'arrête',
            ca: 'Reduir i assegurar-te que el cotxe s\'atura',
            pt: 'Reduzir e certificar-se de que o carro para',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'Never assume a car will stop. Slow down, make eye contact and cross only when it is safe.',
        es: 'Nunca des por hecho que un coche se detendrá. Reduce, haz contacto visual y cruza solo cuando sea seguro.',
        it: 'Non dare mai per scontato che un\'auto si fermi. Rallenta, stabilisci un contatto visivo e attraversa solo quando è sicuro.',
        nl: 'Ga er nooit van uit dat een auto stopt. Vertraag, maak oogcontact en steek pas over als het veilig is.',
        fr: 'Ne supposez jamais qu\'une voiture s\'arrêtera. Ralentissez, établissez un contact visuel et ne traversez que lorsque c\'est sûr.',
        ca: 'No donis mai per fet que un cotxe s\'aturarà. Redueix, estableix contacte visual i creua només quan sigui segur.',
        pt: 'Nunca assuma que um carro vai parar. Reduza, estabeleça contacto visual e atravesse apenas quando for seguro.',
      },
    },
  ],
};
