import type { Module } from '../types';

export const ridingSafely: Module = {
  slug: 'riding-safely',
  title: {
    en: 'Riding Safely',
    es: 'Conducir con seguridad',
    it: 'Guidare in sicurezza',
    nl: 'Veilig rijden',
    fr: 'Rouler en toute sécurité',
    ca: 'Conduir amb seguretat',
    pt: 'Conduzir em segurança',
  },
  subtitle: {
    en: 'Our best tips on how to ride and park safely.',
    es: 'Nuestros mejores consejos para conducir y aparcar con seguridad.',
    it: 'I nostri migliori consigli per guidare e parcheggiare in sicurezza.',
    nl: 'Onze beste tips om veilig te rijden en te parkeren.',
    fr: 'Nos meilleurs conseils pour rouler et stationner en toute sécurité.',
    ca: 'Els nostres millors consells per conduir i aparcar amb seguretat.',
    pt: 'As nossas melhores dicas para conduzir e estacionar em segurança.',
  },
  description: {
    en: 'Safety starts with you. This module covers protective gear, how to behave around others, parking correctly and riding in tricky conditions.',
    es: 'La seguridad empieza por ti. Este módulo trata el equipo de protección, cómo comportarte con los demás, aparcar correctamente y conducir en condiciones difíciles.',
    it: 'La sicurezza inizia da te. Questo modulo tratta l\'equipaggiamento di protezione, come comportarti con gli altri, parcheggiare correttamente e guidare in condizioni difficili.',
    nl: 'Veiligheid begint bij jou. Deze module behandelt beschermende uitrusting, hoe je je tegenover anderen gedraagt, correct parkeren en rijden onder lastige omstandigheden.',
    fr: 'La sécurité commence par vous. Ce module aborde l\'équipement de protection, le comportement envers les autres, le stationnement correct et la conduite dans des conditions difficiles.',
    ca: 'La seguretat comença per tu. Aquest mòdul tracta l\'equip de protecció, com comportar-te amb els altres, aparcar correctament i conduir en condicions difícils.',
    pt: 'A segurança começa em ti. Este módulo aborda o equipamento de proteção, como te comportares com os outros, estacionar corretamente e conduzir em condições difíceis.',
  },
  lessons: [
    {
      title: {
        en: 'Our best safety tips',
        es: 'Nuestros mejores consejos de seguridad',
        it: 'I nostri migliori consigli di sicurezza',
        nl: 'Onze beste veiligheidstips',
        fr: 'Nos meilleurs conseils de sécurité',
        ca: 'Els nostres millors consells de seguretat',
        pt: 'As nossas melhores dicas de segurança',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Keep both hands on the handlebars.',
              es: 'Mantén ambas manos en el manillar.',
              it: 'Tieni entrambe le mani sul manubrio.',
              nl: 'Houd beide handen aan het stuur.',
              fr: 'Gardez les deux mains sur le guidon.',
              ca: 'Mantén les dues mans al manillar.',
              pt: 'Mantém ambas as mãos no guiador.',
            },
            {
              en: 'Never use your phone while riding.',
              es: 'Nunca uses el móvil mientras conduces.',
              it: 'Non usare mai il telefono mentre guidi.',
              nl: 'Gebruik nooit je telefoon tijdens het rijden.',
              fr: 'N\'utilisez jamais votre téléphone en roulant.',
              ca: 'No facis servir mai el mòbil mentre condueixes.',
              pt: 'Nunca uses o telemóvel enquanto conduzes.',
            },
            {
              en: 'Avoid headphones so you can hear traffic.',
              es: 'Evita los auriculares para poder oír el tráfico.',
              it: 'Evita le cuffie per poter sentire il traffico.',
              nl: 'Vermijd koptelefoons zodat je het verkeer kunt horen.',
              fr: 'Évitez les écouteurs pour pouvoir entendre la circulation.',
              ca: 'Evita els auriculars per poder sentir el trànsit.',
              pt: 'Evita os auscultadores para poderes ouvir o trânsito.',
            },
            {
              en: 'Wear a helmet — it protects your head.',
              es: 'Lleva casco: protege tu cabeza.',
              it: 'Indossa il casco: protegge la testa.',
              nl: 'Draag een helm — die beschermt je hoofd.',
              fr: 'Portez un casque : il protège votre tête.',
              ca: 'Porta casc: protegeix el cap.',
              pt: 'Usa capacete: protege a tua cabeça.',
            },
            {
              en: 'Always follow the local traffic rules.',
              es: 'Respeta siempre las normas de tráfico locales.',
              it: 'Rispetta sempre il codice della strada locale.',
              nl: 'Volg altijd de plaatselijke verkeersregels.',
              fr: 'Respectez toujours le code de la route local.',
              ca: 'Respecta sempre les normes de trànsit locals.',
              pt: 'Respeita sempre as regras de trânsito locais.',
            },
          ],
        },
      ],
    },
    {
      title: {
        en: 'Be mindful of others',
        es: 'Ten en cuenta a los demás',
        it: 'Fai attenzione agli altri',
        nl: 'Houd rekening met anderen',
        fr: 'Soyez attentif aux autres',
        ca: 'Tingues en compte els altres',
        pt: 'Tem atenção aos outros',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Share the road and pavement respectfully. Slow down near pedestrians, give space to people with reduced vision or mobility, and park considerately so you never block their path.',
            es: 'Comparte la vía y la acera con respeto. Reduce la velocidad cerca de peatones, deja espacio a personas con visión o movilidad reducida y aparca con consideración para no bloquear su paso.',
            it: 'Condividi la strada e il marciapiede con rispetto. Rallenta vicino ai pedoni, lascia spazio alle persone con vista o mobilità ridotta e parcheggia con attenzione per non bloccare mai il loro passaggio.',
            nl: 'Deel de weg en de stoep met respect. Verminder je snelheid bij voetgangers, geef ruimte aan mensen met een verminderd zicht of beperkte mobiliteit en parkeer met zorg zodat je hun pad nooit blokkeert.',
            fr: 'Partagez la route et le trottoir avec respect. Ralentissez près des piétons, laissez de l\'espace aux personnes à vision ou mobilité réduite, et stationnez avec égard afin de ne jamais bloquer leur passage.',
            ca: 'Comparteix la via i la vorera amb respecte. Redueix la velocitat a prop dels vianants, deixa espai a les persones amb visió o mobilitat reduïda i aparca amb consideració per no bloquejar mai el seu pas.',
            pt: 'Partilha a via e o passeio com respeito. Reduz a velocidade perto de peões, dá espaço a pessoas com visão ou mobilidade reduzida e estaciona com consideração para nunca bloqueares o seu caminho.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Park correctly',
        es: 'Aparca correctamente',
        it: 'Parcheggia correttamente',
        nl: 'Parkeer correct',
        fr: 'Stationnez correctement',
        ca: 'Aparca correctament',
        pt: 'Estaciona corretamente',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Use the kickstand and leave the bike upright.',
              es: 'Usa el caballete y deja la bici en vertical.',
              it: 'Usa il cavalletto e lascia la bici in posizione verticale.',
              nl: 'Gebruik de standaard en zet de fiets rechtop.',
              fr: 'Utilisez la béquille et laissez le vélo à la verticale.',
              ca: 'Fes servir el cavallet i deixa la bici en vertical.',
              pt: 'Usa o descanso e deixa a bicicleta na vertical.',
            },
            {
              en: "Don't block doorways, ramps or pedestrian paths.",
              es: 'No bloquees puertas, rampas ni pasos de peatones.',
              it: 'Non bloccare porte, rampe o passaggi pedonali.',
              nl: 'Blokkeer geen deuren, hellingen of voetpaden.',
              fr: 'Ne bloquez pas les portes, les rampes ni les passages piétons.',
              ca: 'No bloquegis portes, rampes ni passos de vianants.',
              pt: 'Não bloqueies portas, rampas nem passagens de peões.',
            },
            {
              en: 'Use designated parking zones shown in the app.',
              es: 'Usa las zonas de aparcamiento que indica la app.',
              it: 'Usa le zone di parcheggio indicate nell\'app.',
              nl: 'Gebruik de aangewezen parkeerzones die in de app worden getoond.',
              fr: 'Utilisez les zones de stationnement indiquées dans l\'application.',
              ca: 'Fes servir les zones d\'aparcament que indica l\'app.',
              pt: 'Usa as zonas de estacionamento indicadas na app.',
            },
            {
              en: 'Take a photo at the end of the ride to confirm.',
              es: 'Haz una foto al final del trayecto para confirmar.',
              it: 'Scatta una foto alla fine del viaggio per confermare.',
              nl: 'Maak aan het einde van de rit een foto ter bevestiging.',
              fr: 'Prenez une photo à la fin du trajet pour confirmer.',
              ca: 'Fes una foto al final del trajecte per confirmar.',
              pt: 'Tira uma foto no fim do trajeto para confirmar.',
            },
          ],
        },
      ],
    },
    {
      title: {
        en: 'Cooltra zones',
        es: 'Zonas Cooltra',
        it: 'Zone Cooltra',
        nl: 'Cooltra-zones',
        fr: 'Zones Cooltra',
        ca: 'Zones Cooltra',
        pt: 'Zonas Cooltra',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'The app shows virtual zones that affect your ride: No-Riding zones, Slow zones where speed is limited, No-Parking zones, and Parking zones where you can end your ride.',
            es: 'La app muestra zonas virtuales que afectan a tu trayecto: zonas de prohibido circular, zonas lentas donde se limita la velocidad, zonas de prohibido aparcar y zonas de aparcamiento donde puedes finalizar el trayecto.',
            it: 'L\'app mostra zone virtuali che influiscono sul tuo viaggio: zone in cui è vietato circolare, zone lente dove la velocità è limitata, zone in cui è vietato parcheggiare e zone di parcheggio dove puoi terminare il viaggio.',
            nl: 'De app toont virtuele zones die je rit beïnvloeden: zones waar rijden verboden is, langzame zones waar de snelheid beperkt is, zones waar parkeren verboden is en parkeerzones waar je je rit kunt beëindigen.',
            fr: 'L\'application affiche des zones virtuelles qui influencent votre trajet : zones d\'interdiction de circuler, zones lentes où la vitesse est limitée, zones d\'interdiction de stationner et zones de stationnement où vous pouvez terminer votre trajet.',
            ca: 'L\'app mostra zones virtuals que afecten el teu trajecte: zones de prohibit circular, zones lentes on es limita la velocitat, zones de prohibit aparcar i zones d\'aparcament on pots finalitzar el trajecte.',
            pt: 'A app mostra zonas virtuais que afetam o teu trajeto: zonas de circulação proibida, zonas lentas onde a velocidade é limitada, zonas de estacionamento proibido e zonas de estacionamento onde podes terminar o trajeto.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Riding in rain and winter',
        es: 'Conducir con lluvia y en invierno',
        it: 'Guidare sotto la pioggia e in inverno',
        nl: 'Rijden in regen en winter',
        fr: 'Rouler sous la pluie et en hiver',
        ca: 'Conduir amb pluja i a l\'hivern',
        pt: 'Conduzir com chuva e no inverno',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Slow down on wet, icy or gravelly surfaces and brake earlier and more gently. Keep both hands on the handlebars and wear visible or reflective clothing in low light.',
            es: 'Reduce la velocidad en superficies mojadas, heladas o con grava, y frena antes y con más suavidad. Mantén ambas manos en el manillar y lleva ropa visible o reflectante con poca luz.',
            it: 'Rallenta su superfici bagnate, ghiacciate o con ghiaia e frena prima e con più delicatezza. Tieni entrambe le mani sul manubrio e indossa abiti visibili o riflettenti quando c\'è poca luce.',
            nl: 'Verminder je snelheid op natte, ijzige of grindachtige oppervlakken en rem eerder en zachter. Houd beide handen aan het stuur en draag zichtbare of reflecterende kleding bij weinig licht.',
            fr: 'Ralentissez sur les surfaces mouillées, verglacées ou couvertes de gravier et freinez plus tôt et plus doucement. Gardez les deux mains sur le guidon et portez des vêtements visibles ou réfléchissants lorsque la luminosité est faible.',
            ca: 'Redueix la velocitat en superfícies mullades, gelades o amb grava i frena abans i amb més suavitat. Mantén les dues mans al manillar i porta roba visible o reflectant amb poca llum.',
            pt: 'Reduz a velocidade em superfícies molhadas, geladas ou com gravilha e trava mais cedo e com mais suavidade. Mantém ambas as mãos no guiador e usa roupa visível ou refletora quando há pouca luz.',
          },
        },
      ],
    },
  ],
  quiz: [
    {
      prompt: {
        en: 'Why is it important to wear a helmet?',
        es: '¿Por qué es importante llevar casco?',
        it: 'Perché è importante indossare il casco?',
        nl: 'Waarom is het belangrijk om een helm te dragen?',
        fr: 'Pourquoi est-il important de porter un casque ?',
        ca: 'Per què és important portar casc?',
        pt: 'Porque é importante usar capacete?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'It makes you ride faster',
            es: 'Te hace ir más rápido',
            it: 'Ti fa andare più veloce',
            nl: 'Je rijdt er sneller mee',
            fr: 'Il vous fait rouler plus vite',
            ca: 'Et fa anar més ràpid',
            pt: 'Faz-te andar mais depressa',
          },
        },
        {
          id: 'b',
          label: {
            en: 'It reduces the risk of head injury',
            es: 'Reduce el riesgo de lesiones en la cabeza',
            it: 'Riduce il rischio di lesioni alla testa',
            nl: 'Het vermindert het risico op hoofdletsel',
            fr: 'Il réduit le risque de blessure à la tête',
            ca: 'Redueix el risc de lesions al cap',
            pt: 'Reduz o risco de lesões na cabeça',
          },
        },
        {
          id: 'c',
          label: {
            en: 'It is only for racing',
            es: 'Solo es para competiciones',
            it: 'Serve solo per le gare',
            nl: 'Het is alleen voor wedstrijden',
            fr: 'C\'est uniquement pour la compétition',
            ca: 'Només és per a competicions',
            pt: 'Só serve para competições',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'A helmet protects your head and greatly reduces the risk of serious injury in an accident.',
        es: 'El casco protege tu cabeza y reduce mucho el riesgo de lesiones graves en un accidente.',
        it: 'Il casco protegge la testa e riduce notevolmente il rischio di lesioni gravi in caso di incidente.',
        nl: 'Een helm beschermt je hoofd en vermindert sterk het risico op ernstig letsel bij een ongeval.',
        fr: 'Un casque protège votre tête et réduit considérablement le risque de blessure grave en cas d\'accident.',
        ca: 'El casc protegeix el cap i redueix molt el risc de lesions greus en un accident.',
        pt: 'O capacete protege a tua cabeça e reduz muito o risco de lesões graves num acidente.',
      },
    },
    {
      prompt: {
        en: 'Can you ride two people on a Cooltra eBike?',
        es: '¿Puedes ir dos personas en una eBike de Cooltra?',
        it: 'Puoi viaggiare in due su una eBike Cooltra?',
        nl: 'Mag je met twee personen op een Cooltra-eBike rijden?',
        fr: 'Peut-on rouler à deux sur un eBike Cooltra ?',
        ca: 'Pots anar dues persones en una eBike de Cooltra?',
        pt: 'Podes andar com duas pessoas numa eBike da Cooltra?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Yes, if both hold on',
            es: 'Sí, si ambos se sujetan',
            it: 'Sì, se entrambi si tengono',
            nl: 'Ja, als beiden zich vasthouden',
            fr: 'Oui, si les deux se tiennent',
            ca: 'Sí, si tots dos s\'agafen',
            pt: 'Sim, se ambos se segurarem',
          },
        },
        {
          id: 'b',
          label: {
            en: 'No, one person only',
            es: 'No, solo una persona',
            it: 'No, una sola persona',
            nl: 'Nee, slechts één persoon',
            fr: 'Non, une seule personne',
            ca: 'No, només una persona',
            pt: 'Não, apenas uma pessoa',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Yes, if riding slowly',
            es: 'Sí, si vas despacio',
            it: 'Sì, se vai piano',
            nl: 'Ja, als je langzaam rijdt',
            fr: 'Oui, si on roule lentement',
            ca: 'Sí, si vas a poc a poc',
            pt: 'Sim, se andares devagar',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'eBikes are designed for one rider. Carrying a passenger is dangerous and not allowed.',
        es: 'Las eBikes están diseñadas para un solo conductor. Llevar a un pasajero es peligroso y no está permitido.',
        it: 'Le eBike sono progettate per un solo conducente. Trasportare un passeggero è pericoloso e non consentito.',
        nl: 'eBikes zijn ontworpen voor één bestuurder. Een passagier meenemen is gevaarlijk en niet toegestaan.',
        fr: 'Les eBikes sont conçus pour un seul conducteur. Transporter un passager est dangereux et interdit.',
        ca: 'Les eBikes estan dissenyades per a un sol conductor. Portar un passatger és perillós i no està permès.',
        pt: 'As eBikes foram concebidas para um único condutor. Levar um passageiro é perigoso e não é permitido.',
      },
    },
    {
      prompt: {
        en: 'Where should you park your eBike?',
        es: '¿Dónde debes aparcar tu eBike?',
        it: 'Dove dovresti parcheggiare la tua eBike?',
        nl: 'Waar moet je je eBike parkeren?',
        fr: 'Où devez-vous stationner votre eBike ?',
        ca: 'On has d\'aparcar la teva eBike?',
        pt: 'Onde deves estacionar a tua eBike?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'In front of a doorway',
            es: 'Delante de una puerta',
            it: 'Davanti a una porta',
            nl: 'Voor een deuropening',
            fr: 'Devant une entrée',
            ca: 'Davant d\'una porta',
            pt: 'Em frente a uma porta',
          },
        },
        {
          id: 'b',
          label: {
            en: 'In a designated parking zone',
            es: 'En una zona de aparcamiento autorizada',
            it: 'In una zona di parcheggio autorizzata',
            nl: 'In een aangewezen parkeerzone',
            fr: 'Dans une zone de stationnement autorisée',
            ca: 'En una zona d\'aparcament autoritzada',
            pt: 'Numa zona de estacionamento autorizada',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Anywhere on the pavement',
            es: 'En cualquier lugar de la acera',
            it: 'In qualsiasi punto del marciapiede',
            nl: 'Overal op de stoep',
            fr: 'N\'importe où sur le trottoir',
            ca: 'En qualsevol lloc de la vorera',
            pt: 'Em qualquer lugar do passeio',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'Always end your ride in a designated parking zone and never block access for others.',
        es: 'Termina siempre tu trayecto en una zona de aparcamiento autorizada y nunca bloquees el paso a los demás.',
        it: 'Termina sempre il tuo viaggio in una zona di parcheggio autorizzata e non bloccare mai l\'accesso agli altri.',
        nl: 'Beëindig je rit altijd in een aangewezen parkeerzone en blokkeer nooit de toegang voor anderen.',
        fr: 'Terminez toujours votre trajet dans une zone de stationnement autorisée et ne bloquez jamais l\'accès aux autres.',
        ca: 'Acaba sempre el teu trajecte en una zona d\'aparcament autoritzada i no bloquegis mai el pas als altres.',
        pt: 'Termina sempre o teu trajeto numa zona de estacionamento autorizada e nunca bloqueies o acesso aos outros.',
      },
    },
  ],
};
