import type { Module } from '../types';

export const trafficRules: Module = {
  slug: 'traffic-rules',
  title: {
    en: 'Traffic Rules',
    es: 'Normas de tráfico',
    it: 'Codice della strada',
    nl: 'Verkeersregels',
    fr: 'Code de la route',
    ca: 'Normes de trànsit',
    pt: 'Regras de trânsito',
  },
  subtitle: {
    en: 'Learn the law and what applies to eBike riders.',
    es: 'Aprende la ley y lo que se aplica a los conductores de eBike.',
    it: 'Impara la legge e cosa si applica a chi guida una eBike.',
    nl: 'Leer de wet en wat van toepassing is op eBike-rijders.',
    fr: 'Apprenez la loi et ce qui s\'applique aux conducteurs d\'eBike.',
    ca: 'Aprèn la llei i el que s\'aplica als conductors d\'eBike.',
    pt: 'Aprende a lei e o que se aplica aos condutores de eBike.',
  },
  description: {
    en: 'Laws keep all road users safe. This module covers who can ride, where to ride, riding under the influence and key traffic signs. Rules can vary by country.',
    es: 'Las leyes mantienen seguros a todos los usuarios de la vía. Este módulo trata quién puede conducir, dónde conducir, conducir bajo los efectos del alcohol y las señales de tráfico clave. Las normas pueden variar según el país.',
    it: 'Le leggi tengono al sicuro tutti gli utenti della strada. Questo modulo tratta chi può guidare, dove guidare, la guida sotto l\'effetto di sostanze e i principali segnali stradali. Le regole possono variare da Paese a Paese.',
    nl: 'Wetten houden alle weggebruikers veilig. Deze module behandelt wie mag rijden, waar je mag rijden, rijden onder invloed en belangrijke verkeersborden. Regels kunnen per land verschillen.',
    fr: 'Les lois protègent tous les usagers de la route. Ce module aborde qui peut conduire, où conduire, la conduite sous influence et les principaux panneaux de signalisation. Les règles peuvent varier selon le pays.',
    ca: 'Les lleis mantenen segurs tots els usuaris de la via. Aquest mòdul tracta qui pot conduir, on conduir, conduir sota els efectes de l\'alcohol i els senyals de trànsit clau. Les normes poden variar segons el país.',
    pt: 'As leis mantêm todos os utentes da via seguros. Este módulo aborda quem pode conduzir, onde conduzir, conduzir sob a influência de álcool e os sinais de trânsito principais. As regras podem variar consoante o país.',
  },
  localisedByCountry: true,
  lessons: [
    {
      title: {
        en: 'Who can ride?',
        es: '¿Quién puede conducir?',
        it: 'Chi può guidare?',
        nl: 'Wie mag rijden?',
        fr: 'Qui peut conduire ?',
        ca: 'Qui pot conduir?',
        pt: 'Quem pode conduzir?',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Minimum age and licence requirements depend on your country. In most Cooltra markets you must be at least 16 years old. No driving licence is generally required for an eBike. Check the rule shown for your selected country.',
            es: 'La edad mínima y los requisitos de licencia dependen de tu país. En la mayoría de mercados de Cooltra debes tener al menos 16 años. Por lo general no se necesita carné de conducir para una eBike. Consulta la norma que se muestra para tu país.',
            it: 'L\'età minima e i requisiti di patente dipendono dal tuo Paese. Nella maggior parte dei mercati Cooltra devi avere almeno 16 anni. In genere non è richiesta la patente di guida per una eBike. Controlla la regola indicata per il Paese selezionato.',
            nl: 'De minimumleeftijd en rijbewijsvereisten hangen af van je land. In de meeste Cooltra-markten moet je minstens 16 jaar oud zijn. Voor een eBike is doorgaans geen rijbewijs vereist. Controleer de regel die voor het geselecteerde land wordt getoond.',
            fr: 'L\'âge minimum et les exigences de permis dépendent de votre pays. Dans la plupart des marchés Cooltra, vous devez avoir au moins 16 ans. Aucun permis de conduire n\'est généralement requis pour un eBike. Consultez la règle affichée pour le pays sélectionné.',
            ca: 'L\'edat mínima i els requisits de llicència depenen del teu país. A la majoria de mercats de Cooltra has de tenir com a mínim 16 anys. En general no cal carnet de conduir per a una eBike. Consulta la norma que es mostra per al teu país.',
            pt: 'A idade mínima e os requisitos de carta de condução dependem do teu país. Na maioria dos mercados da Cooltra tens de ter pelo menos 16 anos. Geralmente não é necessária carta de condução para uma eBike. Consulta a regra apresentada para o país selecionado.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Where to ride',
        es: 'Dónde conducir',
        it: 'Dove guidare',
        nl: 'Waar te rijden',
        fr: 'Où conduire',
        ca: 'On conduir',
        pt: 'Onde conduzir',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Ride on the right-hand side of the road.',
              es: 'Circula por el lado derecho de la vía.',
              it: 'Guida sul lato destro della strada.',
              nl: 'Rijd aan de rechterkant van de weg.',
              fr: 'Roulez du côté droit de la route.',
              ca: 'Circula pel costat dret de la via.',
              pt: 'Circula pelo lado direito da via.',
            },
            {
              en: 'Use bike lanes where they are available.',
              es: 'Usa los carriles bici donde estén disponibles.',
              it: 'Usa le piste ciclabili dove sono disponibili.',
              nl: 'Gebruik fietspaden waar ze beschikbaar zijn.',
              fr: 'Utilisez les pistes cyclables là où elles sont disponibles.',
              ca: 'Fes servir els carrils bici on estiguin disponibles.',
              pt: 'Usa as ciclovias onde estiverem disponíveis.',
            },
            {
              en: 'Do not ride on pavements or pedestrian areas.',
              es: 'No circules por aceras ni zonas peatonales.',
              it: 'Non guidare sui marciapiedi o nelle aree pedonali.',
              nl: 'Rijd niet op stoepen of in voetgangersgebieden.',
              fr: 'Ne roulez pas sur les trottoirs ni dans les zones piétonnes.',
              ca: 'No circulis per voreres ni zones de vianants.',
              pt: 'Não circules em passeios nem em zonas pedonais.',
            },
            {
              en: 'Avoid fast roads where eBikes are not allowed.',
              es: 'Evita las vías rápidas donde no se permiten eBikes.',
              it: 'Evita le strade veloci dove le eBike non sono ammesse.',
              nl: 'Vermijd snelwegen waar eBikes niet zijn toegestaan.',
              fr: 'Évitez les voies rapides où les eBikes ne sont pas autorisés.',
              ca: 'Evita les vies ràpides on no es permeten les eBikes.',
              pt: 'Evita as vias rápidas onde as eBikes não são permitidas.',
            },
          ],
        },
      ],
    },
    {
      title: {
        en: 'One rider, and never under the influence',
        es: 'Un solo conductor y nunca bajo los efectos',
        it: 'Un solo conducente e mai sotto l\'effetto di sostanze',
        nl: 'Eén rijder, en nooit onder invloed',
        fr: 'Un seul conducteur, et jamais sous influence',
        ca: 'Un sol conductor i mai sota els efectes',
        pt: 'Um só condutor e nunca sob a influência',
      },
      blocks: [
        {
          type: 'paragraph',
          text: {
            en: 'Only one person may ride at a time. Riding under the influence of alcohol or drugs is illegal — the same limits as driving a car apply, and you risk fines or losing your licence.',
            es: 'Solo puede conducir una persona a la vez. Conducir bajo los efectos del alcohol o las drogas es ilegal: se aplican los mismos límites que al conducir un coche, y te arriesgas a multas o a perder el carné.',
            it: 'Può guidare una sola persona alla volta. Guidare sotto l\'effetto di alcol o droghe è illegale: si applicano gli stessi limiti della guida di un\'auto e rischi multe o la perdita della patente.',
            nl: 'Er mag maar één persoon tegelijk rijden. Rijden onder invloed van alcohol of drugs is illegaal — dezelfde limieten als bij het besturen van een auto gelden, en je riskeert boetes of het verlies van je rijbewijs.',
            fr: 'Une seule personne peut conduire à la fois. Conduire sous l\'influence de l\'alcool ou de drogues est illégal — les mêmes limites que pour la conduite d\'une voiture s\'appliquent, et vous risquez des amendes ou le retrait de votre permis.',
            ca: 'Només pot conduir una persona alhora. Conduir sota els efectes de l\'alcohol o les drogues és il·legal: s\'apliquen els mateixos límits que en conduir un cotxe, i t\'arrisques a multes o a perdre el carnet.',
            pt: 'Só pode conduzir uma pessoa de cada vez. Conduzir sob a influência de álcool ou drogas é ilegal — aplicam-se os mesmos limites que ao conduzir um carro, e arriscas-te a multas ou a perder a carta.',
          },
        },
      ],
    },
    {
      title: {
        en: 'Key traffic signs',
        es: 'Señales de tráfico clave',
        it: 'Segnali stradali principali',
        nl: 'Belangrijke verkeersborden',
        fr: 'Panneaux de signalisation essentiels',
        ca: 'Senyals de trànsit clau',
        pt: 'Sinais de trânsito principais',
      },
      blocks: [
        {
          type: 'list',
          items: [
            {
              en: 'Stop sign: come to a complete stop, even if the street looks empty.',
              es: 'Señal de stop: detente por completo, aunque la calle parezca vacía.',
              it: 'Segnale di stop: fermati completamente, anche se la strada sembra vuota.',
              nl: 'Stopbord: kom volledig tot stilstand, ook al lijkt de straat leeg.',
              fr: 'Panneau stop : arrêtez-vous complètement, même si la rue semble vide.',
              ca: 'Senyal d\'stop: atura\'t completament, encara que el carrer sembli buit.',
              pt: 'Sinal de stop: para por completo, mesmo que a rua pareça vazia.',
            },
            {
              en: 'No-entry and no-bikes signs: do not enter.',
              es: 'Señales de prohibido el paso y prohibido bicis: no entres.',
              it: 'Segnali di divieto di accesso e divieto di biciclette: non entrare.',
              nl: 'Verboden-toegang- en verboden-voor-fietsen-borden: niet binnenrijden.',
              fr: 'Panneaux sens interdit et vélos interdits : n\'entrez pas.',
              ca: 'Senyals de prohibit el pas i prohibit bicicletes: no entris.',
              pt: 'Sinais de proibido entrar e proibido bicicletas: não entres.',
            },
            {
              en: 'Give way: let other traffic pass first.',
              es: 'Ceda el paso: deja pasar primero al resto del tráfico.',
              it: 'Dare la precedenza: lascia passare prima gli altri veicoli.',
              nl: 'Voorrang verlenen: laat ander verkeer eerst gaan.',
              fr: 'Cédez le passage : laissez passer les autres usagers d\'abord.',
              ca: 'Cediu el pas: deixa passar primer la resta del trànsit.',
              pt: 'Cedência de passagem: deixa passar primeiro o restante trânsito.',
            },
            {
              en: 'A red traffic light means stop until it turns green.',
              es: 'Un semáforo en rojo significa detenerse hasta que se ponga verde.',
              it: 'Un semaforo rosso significa fermarsi finché non diventa verde.',
              nl: 'Een rood verkeerslicht betekent stoppen totdat het groen wordt.',
              fr: 'Un feu rouge signifie s\'arrêter jusqu\'à ce qu\'il passe au vert.',
              ca: 'Un semàfor en vermell significa aturar-se fins que es posi verd.',
              pt: 'Um semáforo vermelho significa parar até ficar verde.',
            },
          ],
        },
      ],
    },
  ],
  quiz: [
    {
      prompt: {
        en: 'What does a red traffic light mean?',
        es: '¿Qué significa un semáforo en rojo?',
        it: 'Cosa significa un semaforo rosso?',
        nl: 'Wat betekent een rood verkeerslicht?',
        fr: 'Que signifie un feu rouge ?',
        ca: 'Què significa un semàfor en vermell?',
        pt: 'O que significa um semáforo vermelho?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'Stop until green',
            es: 'Detente hasta que se ponga verde',
            it: 'Fermati finché non diventa verde',
            nl: 'Stop totdat het groen wordt',
            fr: 'Arrêtez-vous jusqu\'au vert',
            ca: 'Atura\'t fins que es posi verd',
            pt: 'Para até ficar verde',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Slow down',
            es: 'Reduce la velocidad',
            it: 'Rallenta',
            nl: 'Vertraag',
            fr: 'Ralentissez',
            ca: 'Redueix la velocitat',
            pt: 'Reduz a velocidade',
          },
        },
        {
          id: 'c',
          label: {
            en: 'Stop only if there is traffic',
            es: 'Detente solo si hay tráfico',
            it: 'Fermati solo se c\'è traffico',
            nl: 'Stop alleen als er verkeer is',
            fr: 'Arrêtez-vous seulement s\'il y a du trafic',
            ca: 'Atura\'t només si hi ha trànsit',
            pt: 'Para apenas se houver trânsito',
          },
        },
      ],
      correctOptionId: 'a',
      explanation: {
        en: 'A red light always means stop and wait until it turns green, regardless of traffic.',
        es: 'Un semáforo en rojo siempre significa detenerse y esperar a que se ponga verde, haya o no tráfico.',
        it: 'Un semaforo rosso significa sempre fermarsi e aspettare finché non diventa verde, indipendentemente dal traffico.',
        nl: 'Een rood licht betekent altijd stoppen en wachten totdat het groen wordt, ongeacht het verkeer.',
        fr: 'Un feu rouge signifie toujours s\'arrêter et attendre qu\'il passe au vert, quel que soit le trafic.',
        ca: 'Un semàfor en vermell sempre significa aturar-se i esperar fins que es posi verd, hi hagi o no trànsit.',
        pt: 'Um semáforo vermelho significa sempre parar e esperar até ficar verde, independentemente do trânsito.',
      },
    },
    {
      prompt: {
        en: 'Where should you ride your eBike?',
        es: '¿Dónde debes conducir tu eBike?',
        it: 'Dove dovresti guidare la tua eBike?',
        nl: 'Waar moet je je eBike rijden?',
        fr: 'Où devez-vous conduire votre eBike ?',
        ca: 'On has de conduir la teva eBike?',
        pt: 'Onde deves conduzir a tua eBike?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'On the pavement',
            es: 'Por la acera',
            it: 'Sul marciapiede',
            nl: 'Op de stoep',
            fr: 'Sur le trottoir',
            ca: 'Per la vorera',
            pt: 'No passeio',
          },
        },
        {
          id: 'b',
          label: {
            en: 'In a bike lane or on the road',
            es: 'Por el carril bici o la calzada',
            it: 'In una pista ciclabile o sulla strada',
            nl: 'Op een fietspad of op de weg',
            fr: 'Sur une piste cyclable ou sur la route',
            ca: 'Pel carril bici o la calçada',
            pt: 'Numa ciclovia ou na estrada',
          },
        },
        {
          id: 'c',
          label: {
            en: 'In pedestrian zones',
            es: 'Por zonas peatonales',
            it: 'Nelle zone pedonali',
            nl: 'In voetgangerszones',
            fr: 'Dans les zones piétonnes',
            ca: 'Per zones de vianants',
            pt: 'Em zonas pedonais',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'Ride in bike lanes where available, otherwise on the road. Pavements are for pedestrians.',
        es: 'Circula por el carril bici donde lo haya; si no, por la calzada. Las aceras son para los peatones.',
        it: 'Guida nelle piste ciclabili dove disponibili, altrimenti sulla strada. I marciapiedi sono per i pedoni.',
        nl: 'Rijd op fietspaden waar beschikbaar, anders op de weg. Stoepen zijn voor voetgangers.',
        fr: 'Roulez sur les pistes cyclables là où elles existent, sinon sur la route. Les trottoirs sont pour les piétons.',
        ca: 'Circula pel carril bici on n\'hi hagi; si no, per la calçada. Les voreres són per als vianants.',
        pt: 'Circula nas ciclovias onde existirem, caso contrário na estrada. Os passeios são para os peões.',
      },
    },
    {
      prompt: {
        en: 'If you see a stop sign and the street is empty, should you stop?',
        es: 'Si ves una señal de stop y la calle está vacía, ¿debes parar?',
        it: 'Se vedi un segnale di stop e la strada è vuota, devi fermarti?',
        nl: 'Als je een stopbord ziet en de straat is leeg, moet je dan stoppen?',
        fr: 'Si vous voyez un panneau stop et que la rue est vide, devez-vous vous arrêter ?',
        ca: 'Si veus un senyal d\'stop i el carrer està buit, t\'has d\'aturar?',
        pt: 'Se vires um sinal de stop e a rua estiver vazia, deves parar?',
      },
      options: [
        {
          id: 'a',
          label: {
            en: 'No, just slow down',
            es: 'No, solo reducir la velocidad',
            it: 'No, basta rallentare',
            nl: 'Nee, gewoon vertragen',
            fr: 'Non, ralentissez seulement',
            ca: 'No, només reduir la velocitat',
            pt: 'Não, basta reduzir a velocidade',
          },
        },
        {
          id: 'b',
          label: {
            en: 'Yes, a complete stop is required',
            es: 'Sí, hay que detenerse por completo',
            it: 'Sì, è obbligatorio fermarsi completamente',
            nl: 'Ja, volledig stoppen is verplicht',
            fr: 'Oui, un arrêt complet est obligatoire',
            ca: 'Sí, cal aturar-se per complet',
            pt: 'Sim, é obrigatório parar por completo',
          },
        },
      ],
      correctOptionId: 'b',
      explanation: {
        en: 'A stop sign always requires a complete stop, even when the street looks empty.',
        es: 'Una señal de stop siempre obliga a detenerse por completo, aunque la calle parezca vacía.',
        it: 'Un segnale di stop richiede sempre un arresto completo, anche quando la strada sembra vuota.',
        nl: 'Een stopbord vereist altijd een volledige stop, ook als de straat leeg lijkt.',
        fr: 'Un panneau stop exige toujours un arrêt complet, même lorsque la rue semble vide.',
        ca: 'Un senyal d\'stop sempre obliga a aturar-se per complet, encara que el carrer sembli buit.',
        pt: 'Um sinal de stop exige sempre uma paragem completa, mesmo quando a rua parece vazia.',
      },
    },
  ],
};
